### ISSUE TITLE
Unable to Build Scene for UWP / HoloLens

### ISSUE THREAD

**Issue by Gabweb** [leapmotion/UnityModules#926]
I'm unable to build a scene containing the Core Assets 4.3.3. I'm keep getting errors. There are multiple errors saying, that the type or namespace could not be found. Similar to this one:

`Assets\LeapMotion\Core\Scripts\Hands\TestHandFactory.cs(54,19): error CS0246: The type or namespace name 'Hand' could not be found (are you missing a using directive or an assembly reference?)`

Steps performed:
- Open Unity & Create new Project
- Import Core Assets (and update the APIs)
- Open example scene
- File -> Build Settings ... -> select UWP & Hololens -> Click Build

I'm working on Unity 2017.2f3. Selecting File -> Build & Run works though...

**Comment by Amarcolina** [comment]
Hi @Gabweb !

Unfortunately the UWP / HoloLense platforms are not supported by the UnityModules package at this time.  There are some non-trivial changes that would need to be made to the core services in order to make them compatible, and it's just not at the top of our roadmap right now.

**Comment by Amarcolina** [comment]
I'm going to close this for now.  I'll re-open this if plans change!

**Comment by 265lutab** [comment]
That is unfortunate. I am also wanting to use LeapMotion with UWP.

**Comment by nickjbenson** [comment]
I do want to clarify that applications that target SteamVR can run on UWP for Windows Mixed Reality devices, so it's very possible to run Leap Motion applications on Windows Mixed Reality headsets if your build targets SteamVR (e.g. Vive) support! You don't have to import the SteamVR SDK, you just have to include SteamVR as a supported VR device.

**Comment by Upd4ting** [comment]
Any news about compiling on UWP?

**Comment by Amarcolina** [comment]
Still no plans for official support yet, but recently a change was merged into the develop branch that uploaded the original source files in place of the LeapCSharp dll.  I don't believe that change alone will allow support for UWP, but it may make it easier to modify now that the source is not locked behind a dll.

**Comment by Upd4ting** [comment]
Okay I'll look into it, thanks :)
